[package]
name = "core-synchronization"
version = "0.2.0-beta.2"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "1.2"
ckb-jsonrpc-types = "0.43"
ckb-types = "0.43"
futures = "0.3"
itertools = "0.10"
lazy_static = "1.4"
log = "0.4"
rbatis = { version = "2.1", features = ["all-database", "tokio1"] }
rlp = "0.5"
parking_lot = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.12", features = ["macros", "rt-multi-thread", "sync", "time"] }

common = { path = "../../common" }
core-storage = { path = "../storage" }
db_protocol = { path = "../../db/protocol", package = "protocol" }
db_xsql = { path = "../../db/xsql", package = "xsql" }
db_rocksdb = { path = "../../db/rocksdb", package = "rocksdb" }

[dev-dependencies]
bson = "1.2"
env_logger = "0.9"
