[package]
name = "core-synchronization"
version = "0.1.0"
authors = ["KaoImin <kaoimin@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-jsonrpc-types = "0.43"
ckb-types = "0.43"
futures = "0.3"
log = "0.4"
rbatis = { git = "https://github.com/KaoImin/rbatis.git", branch = "bson", features = ["all-database", "tokio1"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.11", features = ["macros", "rt-multi-thread", "sync", "time"] }

common = { path = "../../common" }
core-storage = { path = "../storage" }
db_protocol = { path = "../../db/protocol", package = "protocol" }
db_xsql = { path = "../../db/xsql", package = "xsql" }
db_rocksdb = { path = "../../db/rocksdb", package = "rocksdb" }

