[package]
name = "core-synchronization"
version = "0.1.0"
authors = ["KaoImin <kaoimin@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-jsonrpc-types = "0.43"
ckb-types = "0.43"
tokio = { version = "1.10", features = ["macros", "rt-multi-thread", "sync"] }

common = { path = "../../common" }
