name-template: '$RESOLVED_VERSION 🌈'

template: '# CHANGES \n $CHANGES'

categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'perf'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🧰 Maintenance'
    labels: 
      - 'refactor'
      - 'chore'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

sort-by: 'title'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

exclude-labels:
  - 'skip-changelog'
