name-template: '$RESOLVED_VERSION 🌈'

template: |
  # Changes

  $CHANGES

categories:
  - title: '🚀 Features'
    labels:
      - 'pr_feat'
      - 'pr_perf'
  - title: '🐛 Bug Fixes'
    labels:
      - 'pr_fix'
  - title: '🧰 Maintenance'
    labels: 
      - 'pr_refactor'
      - 'pr_chore'
  - title: '📝 Document'
    labels:
      - 'pr_docs'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

sort-by: 'title'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

exclude-labels:
  - 'skip_changelog'
