[package]
name = "mercury"
description = "Building on top of ckb-indexer, mercury provides handy integration features for Nervos CKB."
version = "0.1.0-rc.3"
authors = ["Eason Gao <kaoimin@qq.com>, Xuejie Xiao <xxuejie@gmail.com>"]
edition = "2018"

[dependencies]
core-cli = { path = "core/cli" }
tokio = { version = "1.9", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
criterion = { version = "0.3", features = ["async_tokio", "cargo_bench_support"] }
rand = "0.8"

[workspace]
members = [
	"common",
	"core/cli",
	"core/extensions",
	"core/rpc",
	"core/service",
	"core/storage",
	"db/postgres",
	"db/protocol"
]

[profile.release]
lto = true
overflow-checks = true
