[package]
name = "mercury"
description = "Building on top of ckb-indexer, mercury provides handy integration features for Nervos CKB."
version = "0.1.0"
authors = ["Xuejie Xiao <xxuejie@gmail.com>, Eason Gao <kaoimin@qq.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "2.33"
# ckb-indexer = { git = "https://github.com/quake/ckb-indexer", rev = "290ae55" }
ckb-indexer = { git = "https://github.com/KaoImin/ckb-indexer", branch = "impl-error" }
ckb-jsonrpc-types = "0.40"
ckb-types = "0.40"
derive_more = "0.99"
env_logger = "0.8"
futures = "0.3"
hex = "0.4"
jsonrpc-core = "17.0"
jsonrpc-core-client = { version = "17.0", features = ["http", "tls"] }
jsonrpc-derive = "17.0"
jsonrpc-http-server = "17.0"
jsonrpc-server-utils = "17.0"
log = "0.4"
molecule = "=0.6.0"
num-bigint = "0.4"   
num-traits = "0.2" 
rlp = "0.4"
rocksdb = { package = "ckb-rocksdb", version = "=0.15.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.4", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
ckb-chain-spec = "0.40"
criterion = { version = "0.3", features = ["async_tokio", "cargo_bench_support"] }
kvdb = "0.9"
lazy_static = "1.4"
memory-db = { package = "kvdb-memorydb", version = "0.9" }
rand = "0.7"
