[package]
name = "mercury"
description = "Building on top of ckb-indexer, mercury provides handy integration features for Nervos CKB."
version = "0.2.0-beta.2"
authors = ["Nervos Network"]
edition = "2018"

[dependencies]
core-cli = { path = "core/cli" }
log = "0.4"
tokio = { version = "1.12", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
criterion = { version = "0.3", features = ["async_tokio", "cargo_bench_support"] }
rand = "0.8"

[workspace]
members = [
	"apm/tracing",
	"apm/tracing-derive",
	"logger",
	"common",
	"core/cli",
	"core/extensions",
	"core/inspection",
	"core/rpc",
	"core/service",
	"core/storage",
	"core/synchronization",
	"db/protocol",
	"db/rocksdb",
	"db/xsql",
	"db/xsql-test"
]

[profile.release]
lto = true
overflow-checks = true
panic = "abort"
