[package]
name = "mercury"
description = "Building on top of ckb-indexer, mercury provides handy integration features for Nervos CKB."
version = "0.1.0"
authors = ["Xuejie Xiao <xxuejie@gmail.com>, Eason Gao <kaoimin@qq.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
rocksdb = { package = "ckb-rocksdb", version = "=0.15.1" }
# ckb-indexer = { git = "https://github.com/quake/ckb-indexer", rev = "290ae55" }
ckb-indexer = { path = "../ckb-indexer" }
ckb-jsonrpc-types = "0.40.0"
ckb-types = "0.40.0"
molecule = "=0.6.0"
jsonrpc-core = "17.0"
jsonrpc-core-client = { version = "17.0", features = ["http", "tls"] }
jsonrpc-derive = "17.0"
jsonrpc-http-server = "17.0"
jsonrpc-server-utils = "17.0"
futures = "0.3"
clap = "2.33"
rlp = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.8"
tokio = { version = "1.4", features = ["macros", "rt-multi-thread"] }
num-bigint = "0.4"   
num-traits = "0.2" 
derive_more = "0.99"
hex = "0.4"

[dev-dependencies]
rand = "0.7"
criterion = { version = "0.3", features = ["async_tokio", "cargo_bench_support"] }
