[package]
name = "mercury"
description = "Building on top of ckb-indexer, mercury provides handy integration features for Nervos CKB."
version = "0.1.0"
authors = ["Eason Gao <kaoimin@qq.com>, Xuejie Xiao <xxuejie@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.7", features = ["macros", "rt-multi-thread", "time"] }
tokio-compat = { package = "tokio-compat-02", version = "0.2" }

core-cli = { path = "core/cli" }

[dev-dependencies]
criterion = { version = "0.3", features = ["async_tokio", "cargo_bench_support"] }
rand = "0.7"

[workspace]
members = [
	"common",
	"core/cli",
	"core/extensions",
	"core/rpc",
	"core/service",
	"core/storage"
]
