[package]
name = "xsql"
version = "0.1.0"
authors = ["KaoImin <kaoimin@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-jsonrpc-types = "0.43"
ckb-types = "0.43"
clap = "2.33"
log = "0.4"
rbatis = { version = "2.0", features = ["all-database", "tokio1"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

common = { path = "../../common" }
db_protocol = { path = "../protocol", package = "protocol" }

[features]
postgres = ["rbatis/postgres"]
