[package]
name = "core-storage"
version = "0.1.0"
authors = ["KaoImin <kaoimin@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ckb-indexer = { git = "https://github.com/nervosnetwork/ckb-indexer", rev = "d247556" }
ckb-indexer = { git = "https://github.com/KaoImin/ckb-indexer", branch = "mercury" }
ckb-types = "0.43"

common = { path = "../../common" }
