[package]
name = "core-cli"
version = "0.2.0-beta.2"
authors = ["Nervos Network"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
ckb-types = "0.43"
ckb-jsonrpc-types = "0.43"
clap = "2.33"
fs_extra = "1.2"
log = "0.4"
log4rs = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.12", features = ["time"] }
toml = "0.5"

common = { path = "../../common" }
common-logger = { path = "../../logger" }
core-extensions = { path = "../extensions" }
core-service = { path = "../service" }

[dev-dependencies]
rand = "0.8"
