[package]
name = "core-service"
version = "0.1.0"
authors = ["KaoImin <kaoimin@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ckb-indexer = { git = "https://github.com/nervosnetwork/ckb-indexer", rev = "d247556" }
ckb-indexer = { git = "https://github.com/KaoImin/ckb-indexer", branch = "mercury" }
# ckb-indexer = { path = "../ckb-indexer" }
ckb-jsonrpc-types = "0.43"
ckb-types = "0.43"
jsonrpc-core = "18.0"
jsonrpc-http-server = "18.0"
jsonrpc-server-utils = "18.0"
lazy_static = "1.4"
log = "0.4"
rocksdb = { package = "ckb-rocksdb", version = "0.16" }
tokio = { version = "1.11", features = ["macros", "rt-multi-thread", "time"] }

common = { path = "../../common" }
core-extensions = { path = "../extensions" }
core-rpc = { path = "../rpc" }
core-storage = { path = "../storage" }
