[package]
name = "common"
version = "0.1.0"
authors = ["KaoImin <kaoimin@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
derive_more = "0.99"
ckb-sdk = "0.42"
ckb-types = "0.42"
num-bigint = "0.4"

[dev-dependencies]
rand = "0.7"
