# The network type reference https://github.com/nervosnetwork/ckb-cli/blob/master/ckb-sdk/src/constants.rs
network_type = "ckb_testnet"

# log_level = "DEBUG"

# store_path = "./free-space/db"

# snapshot_path = "./free-space/snapshot"

# snapshot_interval = 1000

# Fill cellbase maturity in the same as the ckb genesis block.
cellbase_maturity = 4

cheque_since = 6

log_path = "./free-space/mercury.log"

ckb_uri = "http://127.0.0.1:8114"

listen_uri = "0.0.0.0:8116"

# The secp256k1_blake160 script info is indispensable.
[[extensions_config]]
extension_name = "ckb_balance"

[[extensions_config.scripts]]
name = "secp256k1_blake160"
script = '''
{
    "args": "0x",
    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "dep_group",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37"
    }
}
'''

[[extensions_config]]
extension_name = "udt_balance"

[[extensions_config.scripts]]
name = "sudt_balance"
script = '''
{
    "args": "0x",
    "code_hash": "0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0xe12877ebd2c3c364dc46c5c992bcfaf4fee33fa13eebdf82c591fc9825aab769"
    }
}
'''

# The xUDT script config is dummy
[[extensions_config.scripts]]
name = "xudt_balance"
script = '''
{
    "args": "0x",
    "code_hash": "0x517ce23bca5a398d4b3180fd35223d45befab6e008613f4a0f4bd5cc0f531d81",
    "hash_type": "data"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0x31fb8209f5ffe247438e3eb19070b8f309b035c0969a65643ad96fca0da2ffec"
    }
}
'''

[[extensions_config]]
extension_name = "special_cells"

[[extensions_config.scripts]]
name = "anyone_can_pay"
script = '''
{
    "args": "0x",
    "code_hash": "0xd369597ff47f29fbc0d47d2e3775370d1250b85140c670e4718af712983a2354",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "dep_group",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0x4153a2014952d7cac45f285ce9a7c5c0c0e1b21f2d378b82ac1433cb11c25c4d"
    }
}
'''

[[extensions_config.scripts]]
name = "cheque"
script = '''
{
    "args": "0x",
    "code_hash": "0x9f27f3afc8d26dfa8bc0c8fa21bc033ddcdab6ad83d5e865cdd6d5d0b3b95642",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "dep_group",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0x1dbbeac82db9a330ed07dd33e547facbca14378196f0e2d69ad8e83bce1d5f54"
    }
}
'''
