# The network type reference https://github.com/nervosnetwork/ckb-cli/blob/master/ckb-sdk/src/constants.rs
network_type = "ckb_testnet"

# log_level = "DEBUG"

# store_path = "./free-space/db"

ckb_uri = "http://127.0.0.1:8114"

listen_uri = "0.0.0.0:8116"

# extensions config
[[extensions_config]]
extension_name = "ckb_balance"
scripts = []

[[extensions_config]]
extension_name = "udt_balance"

[[extensions_config.scripts]]
name = "sudt_balance"
script = '''
{
    "args": "0x",
    "code_hash": "0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4",
    "hash_type": "data"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0xa4037a893eb48e18ed4ef61034ce26eba9c585f15c9cee102ae58505565eccc3"
    }
}
'''

# The xUDT script config is dummy
[[extensions_config.scripts]]
name = "xudt_balance"
script = '''
{
    "args": "0x",
    "code_hash": "0x517ce23bca5a398d4b3180fd35223d45befab6e008613f4a0f4bd5cc0f531d81",
    "hash_type": "data"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0x31fb8209f5ffe247438e3eb19070b8f309b035c0969a65643ad96fca0da2ffec"
    }
}
'''
