sync_mode = true

allow_parallel_sync  = true

rpc_thread_num = 3

flush_tx_pool_cache_interval = 300

# Fill cellbase maturity in the same as the ckb genesis block.
cellbase_maturity = 4

cheque_since = 6

pool_cache_size = 100

is_pprof_enabled = false

[db_config]
# Use your pgsql configuration
center_id = 0
machine_id = 0
max_connections = 100
min_connections = 0
connect_timeout = 60
max_lifetime = 1800
idle_timeout = 30
db_type = "postgres"
db_host = "postgres"
db_port = 5432
db_name = "mercury"
db_user = "postgres"
password = "123456"
db_log_level = "WARN"


[log_config]
log_level = "INFO"
auto_split_log_file = true
log_path = "./free-space/mainnet/log"


# The network type reference https://github.com/nervosnetwork/ckb-cli/blob/master/ckb-sdk/src/constants.rs
[network_config]
network_type = "ckb"
# Use the url of the ckb node
ckb_uri = "http://ckb-node:9115"
listen_uri = "0.0.0.0:8116"


[sync_config]
sync_block_batch_size = 1000
max_task_number = 4     # same as the number of cpu cores in the Recommended Hardware section of the README


[[builtin_scripts]]
script_name = "secp256k1_blake160"
script = '''
{
    "args": "0x",
    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "dep_group",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0x71a7ba8fc96349fea0ed3a5c47992e3b4084b031a42264a018e0072e8172e46c"
    }
}
'''


[[builtin_scripts]]
script_name = "sudt"
script = '''
{
    "args": "0x",
    "code_hash": "0x5e7a36a77e68eecc013dfa2fe6a23f3b6c344b04005808694ae6dd45eea4cfd5",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0xc7813f6a415144643970c2e88e0bb6ca6a8edc5dd7c1022746f628284a9936d5"
    }
}
'''


[[builtin_scripts]]
script_name = "anyone_can_pay"
script = '''
{
    "args": "0x",
    "code_hash": "0xd369597ff47f29fbc0d47d2e3775370d1250b85140c670e4718af712983a2354",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "dep_group",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0x4153a2014952d7cac45f285ce9a7c5c0c0e1b21f2d378b82ac1433cb11c25c4d"
    }
}
'''

[[builtin_scripts]]
script_name = "cheque"
script = '''
{
    "args": "0x",
    "code_hash": "0xe4d4ecc6e5f9a059bf2f7a82cca292083aebc0c421566a52484fe2ec51a9fb0c",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "dep_group",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0x04632cc459459cf5c9d384b43dee3e36f542a464bdd4127be7d6618ac6f8d268"
    }
}
'''

[[builtin_scripts]]
script_name = "dao"
script = '''
{
    "args": "0x",
    "code_hash": "0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x2",
        "tx_hash": "0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c"
    }
}
'''

[[builtin_scripts]]
script_name = "pw_lock"
script = '''
{
    "args": "0x",
    "code_hash": "0xbf43c3602455798c1a61a596e0d95278864c552fafe231c063b3fabf97a8febc",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0x1d60cb8f4666e039f418ea94730b1a8c5aa0bf2f7781474406387462924d15d4"
    }
}
'''
