# The network type reference https://github.com/nervosnetwork/ckb-cli/blob/master/ckb-sdk/src/constants.rs
network_type = "ckb_testnet"

# log_level = "DEBUG"

store_path = "./free-space/testnet/db"

snapshot_path = "./free-space/testnet/snapshot"

snapshot_interval = 50000

# rpc_thread_num = 2

# Fill cellbase maturity in the same as the ckb genesis block.
cellbase_maturity = 4

cheque_since = 6

log_path = "./free-space/testnet/mercury.log"

ckb_uri = "http://8.210.169.63:8114"

listen_uri = "0.0.0.0:8116"

# The secp256k1_blake160 script info is indispensable.
[[extensions_config]]
extension_name = "ckb_balance"

[[extensions_config.scripts]]
name = "secp256k1_blake160"
script = '''
{
    "args": "0x",
    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "dep_group",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37"
    }
}
'''

[[extensions_config.scripts]]
name = "sudt_balance"
script = '''
{
    "args": "0x",
    "code_hash": "0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0xe12877ebd2c3c364dc46c5c992bcfaf4fee33fa13eebdf82c591fc9825aab769"
    }
}
'''

[[extensions_config]]
extension_name = "udt_balance"

[[extensions_config.scripts]]
name = "sudt_balance"
script = '''
{
    "args": "0x",
    "code_hash": "0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0xe12877ebd2c3c364dc46c5c992bcfaf4fee33fa13eebdf82c591fc9825aab769"
    }
}
'''

# The xUDT script config is dummy
[[extensions_config.scripts]]
name = "xudt_balance"
script = '''
{
    "args": "0x",
    "code_hash": "0x517ce23bca5a398d4b3180fd35223d45befab6e008613f4a0f4bd5cc0f531d81",
    "hash_type": "data"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0x31fb8209f5ffe247438e3eb19070b8f309b035c0969a65643ad96fca0da2ffec"
    }
}
'''

[[extensions_config]]
extension_name = "special_cells"

[[extensions_config.scripts]]
name = "anyone_can_pay"
script = '''
{
    "args": "0x",
    "code_hash": "0x3419a1c09eb2567f6552ee7a8ecffd64155cffe0f1796e6e61ec088d740c1356",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "dep_group",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0xec26b0f85ed839ece5f11c4c4e837ec359f5adc4420410f6453b1f6b60fb96a6"
    }
}
'''

[[extensions_config.scripts]]
name = "cheque"
script = '''
{
    "args": "0x",
    "code_hash": "0x60d5f39efce409c587cb9ea359cefdead650ca128f0bd9cb3855348f98c70d5b",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "dep_group",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0x7f96858be0a9d584b4a9ea190e0420835156a6010a5fde15ffcdc9d9c721ccab"
    }
}
'''
