[package]
name = "db-sqlx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
once_cell = "1.10"
sqlx = { version = "0.5", features = [ "runtime-tokio-native-tls" , "postgres", "sqlite" ] }
tokio = { version = "1", features = ["full"] }

common = { path = "../../common" }
protocol = { path = "../../protocol" }
