[package]
name = "integration"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
inventory = "0.2"
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0"
