name: Integration test

on:
  workflow_dispatch:

jobs:
  run-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Run integration test
        run: |
          cd tests
          MERCURY_TESTNET_HOST=${{ secrets.MERCURY_TESTNET_HOST }} cargo test
